--Q1. What is the total revenue generated by male vs female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2) AS avg_purchase_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
	   ROUND(SUM(purchase_amount),2) AS total_revenue,
       ROUND(AVG(purchase_amount),2) AS avg_spend
from customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE 
	   						WHEN discount_applied = 'Yes' 
							THEN 1 ELSE 0 END)
							/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
limit 5;


--Q7. Segment customers into (New, Returning, and Loyal) based on their total 
-- number of previous purchases, and show the count of each segment. 
SELECT
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) as number_of_customers
FROM customer
GROUP BY customer_segment
ORDER BY number_of_customers desc;


--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) desc) as item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
from customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


--Q10. What is the revenue contribution of each age group? 
select 
    age_group,
    SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;


--Q11. Which product category generates the highest average purchase amount?
SELECT
    category,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM customer
GROUP BY category
ORDER BY average_purchase_amount DESC;


--Q12. Rank customers based on their purchase amount from highest to lowest.
SELECT
    customer_id,
    SUM(purchase_amount) AS total_purchase,
    DENSE_RANK() OVER (ORDER BY SUM(purchase_amount) DESC) AS purchase_rank
FROM customer
GROUP BY customer_id;


--Q13. For each age group, find the percentage contribution to the total revenue.
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue,
    ROUND(
        SUM(purchase_amount) * 100.0 /
        SUM(SUM(purchase_amount)) OVER (),
        2
    ) AS revenue_percentage
FROM customer
GROUP BY age_group
ORDER BY revenue_percentage DESC;


--Q14. Which 10 locations generate the most revenue, and what's the average order value in each?
SELECT location,
       COUNT(customer_id) AS total_orders,
       SUM(purchase_amount) AS total_revenue,
       ROUND(AVG(purchase_amount),2) AS avg_order_value
FROM customer
GROUP BY location
ORDER BY total_revenue DESC
LIMIT 10;


--Q15. How does revenue and average order value shift by season, 
--and what % of total revenue does each season contribute?
SELECT season,
       COUNT(*) AS total_orders,
       SUM(purchase_amount) AS total_revenue,
       ROUND(AVG(purchase_amount),2) AS avg_purchase_amount,
       ROUND(100.0 * SUM(purchase_amount) / SUM(SUM(purchase_amount)) OVER (),2) AS pct_of_total_revenue
FROM customer
GROUP BY season
ORDER BY total_revenue DESC;


--Q16. Which purchase-frequency segments drive the most revenue, 
--and who are the high-value-but-infrequent customers worth winning back?
-- Revenue by frequency segment
SELECT frequency_of_purchases,
       COUNT(*) AS customers,
       SUM(purchase_amount) AS total_revenue,
       ROUND(AVG(purchase_amount),2) AS avg_spend
FROM customer
GROUP BY frequency_of_purchases
ORDER BY total_revenue DESC;

-- High-value, low-frequency customers (win-back list)
SELECT customer_id, purchase_amount, frequency_of_purchases
FROM customer
WHERE frequency_of_purchases IN ('Annually','Every 3 Months')
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer)
ORDER BY purchase_amount DESC;


--Q17. Which payment methods are most used, and do certain methods correlate with higher average spend?
SELECT payment_method,
       COUNT(*) AS total_transactions,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (),2) AS pct_of_transactions,
       ROUND(AVG(purchase_amount),2) AS avg_spend
FROM customer
GROUP BY payment_method
ORDER BY total_transactions DESC;


--Q18. What's the best-selling size within each product category?
WITH size_counts AS (
    SELECT category, size,
           COUNT(*) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rnk
    FROM customer
    GROUP BY category, size
)
SELECT category, size, total_orders
FROM size_counts
WHERE rnk = 1;


--Q19. What are the top 5 best-selling colors overall, and how much revenue do they generate?
SELECT color,
       COUNT(*) AS total_orders,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY color
ORDER BY total_orders DESC
LIMIT 5;


--Q20. What's the estimated customer lifetime value (CLV) for subscribers vs. non-subscribers?
SELECT subscription_status,
       ROUND(AVG(previous_purchases),2) AS avg_previous_purchases,
       ROUND(AVG(previous_purchases * purchase_amount),2) AS avg_estimated_clv
FROM customer
GROUP BY subscription_status;